### ISSUE TITLE
Use other webproviders outside of autoscout

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/as24#31]

**Comment by Practical-DQ** [comment]
There are othr car web providers, like .... Mobile.de, autotrader.co.uk how much adaptation work is needed to onboard the other services

**Comment by Practical-DQ** [comment]
Extend other providers to include Schwacke or wirkaufendeinauto.de

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#13
