### ISSUE TITLE
Add filter (or segment) on car age (erst-Zulassung)

### ISSUE THREAD

**Issue by chriskli** [Elemetric/as24#42]
all
from now: 5 years in the past
from now: 4 years in the past
from now: 3 years in the past
from now: 2 years in the past
from now: 1 years in the past
from now: 0,5 years in the past

**Comment by Practical-DQ** [comment]
Agree, shoulfd be added to the filter blck at the top

**Comment by Practical-DQ** [comment]
don't agree: but have alternativ suggestion, the band like the price band highlight a set of data. but the time band is vertical where as the price band is horizontal

**Comment by chriskli** [comment]
Für mich ist das Alter des Auto sehr wohl ein Filterkriterium.

**Comment by Practical-DQ** [comment]
why? the price band will show you the youngest and oldest car you can get

**Comment by chriskli** [comment]
because I want it. and i don´t want to look first at the price band, force my brain to understand what i see. I am interested only in 1 year old cars ...

**Comment by Practical-DQ** [comment]
Understood, enhancement?

**Comment by chriskli** [comment]
enhancement!

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#10
