### ISSUE TITLE
when doing a research of car data, the browser is not displaying the data

### ISSUE THREAD

**Issue by chriskli** [Elemetric/as24#61]
when doing a research on Ford Focus the terminal shows 100% of the retrieved data (18.001 records) but the browser remains un the "load data modus".
only a total refresh of the browser (F5) allows to look for cars again and then the data are presented in the browser (but again, geo data are still not possible)

**Comment by danielkagemann** [comment]
please check with next version

**Comment by Practical-DQ** [comment]
Bug still exists in current build

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#8
