### ISSUE TITLE
still not able to get all Golf data

### ISSUE THREAD

**Issue by chriskli** [Elemetric/as24#63]
When trying to get all dat from VW Golf (alle) the server restarts the request by ca. 55%. No data retrieval and no graph is possible.

<img width="382" alt="bildschirmfoto 2016-02-12 um 08 35 11" src="https://cloud.githubusercontent.com/assets/6191778/13001217/cc6dadba-d163-11e5-949c-1e18172043ca.png">

**Comment by chriskli** [comment]
when restarting the terminal, after hours and reboot of the computer, i am able to retrieve all data. Maybe it is a memory problem?

**Comment by Practical-DQ** [comment]
Can Retrieve all data, but no graph is shown (Build vom 2016-02-12-23:25:13 IE11)

**Comment by Practical-DQ** [comment]
Is this bug still open?

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#6
