### ISSUE TITLE
golf data are not shown in full screen (see screenshot)

### ISSUE THREAD

**Issue by chriskli** [Elemetric/as24#65]
Golf data are not using all available space, when going into table view and then back to graph view, it is better.
<img width="1251" alt="bildschirmfoto 2016-02-13 um 11 29 01" src="https://cloud.githubusercontent.com/assets/6191778/13027186/3d0879d8-d245-11e5-9164-075743e71947.png">

**Comment by chriskli** [comment]
still remains with new version

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#5
