### ISSUE TITLE
Storage of Meta Data Information

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/as24#66]
Instead of just polling for the current information we should store the meta data from each search. 
This would give us two immediate benefit
A) The data set of wheich we use for the graphs will of course get bigger and more representative of the market
B) We can make a time analysis, and see how long cars remain on the market.

Still a greyzone of which data we would be allowed to store

**Comment by chriskli** [comment]
Hier möchte ich daran erinnern, dass es bei as24 laut AGBs nicht erlaubt ist, irgendwelche Daten zu ziehen oder zu speichern. Das dürfte sich auch auf die Metadaten beziehen.

**Comment by danielkagemann** [comment]
This issue was moved to Elemetric/cadavis#4
